# Generated by Django 3.0.5 on 2020-06-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllSpieces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Angle180',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipe_diam', models.FloatField(verbose_name='pipe_diam')),
                ('install_length', models.FloatField(verbose_name='installation length in mm')),
            ],
        ),
        migrations.CreateModel(
            name='Angle90',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipe_diam', models.FloatField(verbose_name='pipe_diam')),
                ('install_length', models.FloatField(verbose_name='installation length in mm')),
            ],
        ),
        migrations.CreateModel(
            name='Caps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipe_diam', models.FloatField(verbose_name='pipe_diam')),
                ('install_length', models.FloatField(verbose_name='installation length in mm')),
                ('TValueinterval', models.FloatField(null=True, verbose_name='T value <= ')),
                ('install_length_T', models.FloatField(null=True, verbose_name='installation length in mm')),
            ],
        ),
        migrations.CreateModel(
            name='Flange11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipe_diam', models.FloatField(verbose_name='pipe_diam')),
                ('PN212', models.FloatField(null=True, verbose_name='PN 2,5')),
                ('PN6', models.FloatField(null=True, verbose_name='PN 6')),
                ('PN10', models.FloatField(null=True, verbose_name='PN 10')),
                ('PN16', models.FloatField(null=True, verbose_name='PN 16')),
                ('PN25', models.FloatField(null=True, verbose_name='PN 25')),
                ('PN40', models.FloatField(null=True, verbose_name='PN 40')),
                ('PN63', models.FloatField(null=True, verbose_name='PN 63')),
                ('PN100', models.FloatField(null=True, verbose_name='PN 100')),
                ('PN160', models.FloatField(null=True, verbose_name='PN 160')),
                ('PN250', models.FloatField(null=True, verbose_name='PN 250')),
                ('PN320', models.FloatField(null=True, verbose_name='PN 320')),
                ('PN400', models.FloatField(null=True, verbose_name='PN 400')),
            ],
        ),
        migrations.CreateModel(
            name='Flange13',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipe_diam', models.FloatField(verbose_name='pipe_diam')),
                ('PN212', models.FloatField(null=True, verbose_name='PN 2,5')),
                ('PN6', models.FloatField(null=True, verbose_name='PN 6')),
                ('PN10', models.FloatField(null=True, verbose_name='PN 10')),
                ('PN16', models.FloatField(null=True, verbose_name='PN 16')),
                ('PN25', models.FloatField(null=True, verbose_name='PN 25')),
                ('PN40', models.FloatField(null=True, verbose_name='PN 40')),
                ('PN63', models.FloatField(null=True, verbose_name='PN 63')),
                ('PN100', models.FloatField(null=True, verbose_name='PN 100')),
            ],
        ),
        migrations.CreateModel(
            name='Flange2with35',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipe_diam', models.FloatField(verbose_name='pipe_diam')),
                ('PN212', models.FloatField(null=True, verbose_name='PN 2,5')),
                ('PN6', models.FloatField(null=True, verbose_name='PN 6')),
                ('PN10', models.FloatField(null=True, verbose_name='PN 10')),
                ('PN16', models.FloatField(null=True, verbose_name='PN 16')),
                ('PN25', models.FloatField(null=True, verbose_name='PN 25')),
                ('PN40', models.FloatField(null=True, verbose_name='PN 40')),
            ],
        ),
        migrations.CreateModel(
            name='InsertFlang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipe_diam', models.FloatField(verbose_name='pipe diameter')),
                ('ibs150', models.FloatField(null=True, verbose_name='150 ibs')),
                ('ibs300', models.FloatField(null=True, verbose_name='300 ibs')),
                ('ibs600', models.FloatField(null=True, verbose_name='600 ibs')),
                ('ibs900', models.FloatField(null=True, verbose_name='900 ibs')),
                ('ibs1500', models.FloatField(null=True, verbose_name='1500 ibs')),
            ],
        ),
        migrations.CreateModel(
            name='Reducer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipe_diam_big', models.FloatField(verbose_name='diameter of big pipe')),
                ('install_length_inch', models.FloatField(verbose_name='Installation length in inches')),
                ('install_length_mm', models.FloatField(verbose_name='Installation length in mm')),
                ('small_pipe_diam1', models.FloatField(verbose_name='first small diameter')),
                ('small_pipe_diam2', models.FloatField(verbose_name='second small diameter')),
                ('small_pipe_diam3', models.FloatField(null=True, verbose_name='third small diameter')),
                ('small_pipe_diam4', models.FloatField(null=True, verbose_name='fourth small diameter')),
                ('small_pipe_diam5', models.FloatField(null=True, verbose_name='fifth small diameter')),
                ('small_pipe_diam6', models.FloatField(null=True, verbose_name='sixth small diameter')),
            ],
        ),
        migrations.CreateModel(
            name='ReducerDIN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipe_diam_big', models.FloatField(verbose_name='pipe_diam big')),
                ('pipe_diam_small', models.FloatField(verbose_name='pipe_diam small')),
                ('install_length', models.FloatField(verbose_name='install_length for in mm')),
            ],
        ),
        migrations.CreateModel(
            name='TPiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipe_diam', models.FloatField(verbose_name='pipe diameter')),
                ('install_length', models.FloatField(verbose_name='installation length')),
            ],
        ),
        migrations.CreateModel(
            name='TPieceDIN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipe_diam', models.FloatField(verbose_name='pipe_diam')),
                ('install_length', models.FloatField(verbose_name='installation length in mm')),
            ],
        ),
        migrations.CreateModel(
            name='TReducer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipe_diam_big', models.FloatField(verbose_name=' big pipe diameter')),
                ('pipe_diam_small', models.FloatField(verbose_name='small pipe diameter')),
                ('install_length_big', models.FloatField(verbose_name='M1 in mm')),
                ('install_length_small', models.FloatField(verbose_name='M2 in mm')),
            ],
        ),
        migrations.CreateModel(
            name='TReducerPieceDIN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipe_diam_big', models.FloatField(verbose_name='pipe_diam big')),
                ('pipe_diam_small', models.FloatField(verbose_name='pipe_diam small')),
                ('install_length_big', models.FloatField(verbose_name='install_length for big center pipe in mm')),
                ('install_length_small', models.FloatField(verbose_name='install_length for small center pipe in mm')),
            ],
        ),
        migrations.CreateModel(
            name='Valve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipe_diam', models.FloatField(verbose_name='pipe diameter')),
                ('valve_150ibs', models.FloatField(verbose_name='Gate valve 150 ibs')),
                ('valve_300ibs', models.FloatField(null=True, verbose_name='Gate valve 300 ibs')),
                ('ball_150ibs', models.FloatField(null=True, verbose_name='Ball valve 150 ibs')),
                ('ball_300ibs', models.FloatField(null=True, verbose_name='Ball valve 300 ibs')),
                ('check_150ibs', models.FloatField(null=True, verbose_name='Check valve 150 ibs')),
                ('check_300ibs', models.FloatField(null=True, verbose_name='Check valve 300 ibs')),
            ],
        ),
        migrations.CreateModel(
            name='WeldingBend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipe_diam', models.FloatField(verbose_name='pipe diameter')),
                ('L_R_90_R', models.FloatField(verbose_name='L.R. 90° R')),
                ('L_R_45_B', models.FloatField(null=True, verbose_name='L.R. 45° B')),
                ('L_R_180', models.FloatField(null=True, verbose_name='L.R. 180°')),
                ('S_R_180', models.FloatField(null=True, verbose_name='L.R. 180°')),
                ('S_R_90_A', models.FloatField(null=True, verbose_name='S.R. 90° A')),
            ],
        ),
        migrations.CreateModel(
            name='WeldingNeckFlangASAASTM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipe_diam', models.FloatField(verbose_name='pipe diameter')),
                ('lbs150RF1_16_H', models.FloatField(verbose_name='150 lbs. 1/16 RF. H')),
                ('lbs300RF1_16_H', models.FloatField(verbose_name='300 lbs. 1/16 RF. H')),
                ('lbs400RF1_4_H', models.FloatField(verbose_name='400 lbs. 1/4 RF. H')),
                ('lbs600RF1_4_H', models.FloatField(verbose_name='600 lbs. 1/4 RF. H')),
                ('lbs900RF1_4_H', models.FloatField(null=True, verbose_name='900 lbs. 1/4 RF. H')),
                ('lbs1500RF1_4_H', models.FloatField(null=True, verbose_name='1500 lbs. 1/4 RF. H')),
                ('lbs2500RF1_4_H', models.FloatField(null=True, verbose_name='2500 lbs. 1/4 RF. H')),
            ],
        ),
        migrations.CreateModel(
            name='WeldingNeckFlangDIN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipe_diam', models.FloatField(verbose_name='pipe diameter')),
                ('DIN2632ND10h', models.FloatField(null=True, verbose_name='DIN 2632 ND 10 h')),
                ('DIN2633ND16h', models.FloatField(null=True, verbose_name='DIN 2633 ND 16 h')),
                ('DIN2634ND25h', models.FloatField(null=True, verbose_name='DIN 2634 ND 25 h')),
                ('DIN2635ND40h', models.FloatField(null=True, verbose_name='DIN 2635 ND 40 h')),
                ('DIN2636ND64h', models.FloatField(null=True, verbose_name='DIN 2636 ND 64 h')),
                ('DIN2637ND100h', models.FloatField(null=True, verbose_name='DIN 2637 ND 100 h')),
                ('length', models.FloatField(verbose_name='Length in mm')),
            ],
        ),
        migrations.CreateModel(
            name='Weldolet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipe_diam', models.FloatField(verbose_name='pipe diameter')),
                ('size', models.CharField(max_length=20, verbose_name='Size')),
                ('weldolet_diam1', models.FloatField(null=True, verbose_name='weldolet diameter is 3/8')),
                ('weldolet_diam2', models.FloatField(verbose_name='weldolet diameter is 1/2')),
                ('weldolet_diam3', models.FloatField(null=True, verbose_name='weldolet diameter is 3/4')),
                ('weldolet_diam4', models.FloatField(null=True, verbose_name='weldolet diameter is 1')),
                ('weldolet_diam5', models.FloatField(null=True, verbose_name='weldolet diameter is 1.5')),
                ('weldolet_diam6', models.FloatField(null=True, verbose_name='weldolet diameter is 2')),
                ('weldolet_diam7', models.FloatField(null=True, verbose_name='weldolet diameter is 3')),
                ('weldolet_diam8', models.FloatField(null=True, verbose_name='weldolet diameter is 4')),
                ('weldolet_diam9', models.FloatField(null=True, verbose_name='weldolet diameter is 6')),
                ('weldolet_diam10', models.FloatField(null=True, verbose_name='weldolet diameter is 8')),
                ('weldolet_diam11', models.FloatField(null=True, verbose_name='weldolet diameter is 10')),
                ('weldolet_diam12', models.FloatField(null=True, verbose_name='weldolet diameter is 12')),
                ('weldolet_diam13', models.FloatField(null=True, verbose_name='weldolet diameter is 14')),
                ('weldolet_diam14', models.FloatField(null=True, verbose_name='weldolet diameter is 16')),
                ('weldolet_diam15', models.FloatField(null=True, verbose_name='weldolet diameter is 18')),
                ('weldolet_diam16', models.FloatField(null=True, verbose_name='weldolet diameter is 20')),
                ('weldolet_diam17', models.FloatField(null=True, verbose_name='weldolet diameter is 24')),
            ],
        ),
    ]
